services:
  supaheroes_website:
    user: '${NODE_UID}:${NODE_UID}'
    image: supaheroes_website:1.0.0
    container_name: supaheroes_website
    networks:
      - supaheroes-webserver-network
    build:
      context: ./
      args:
        NODE_UID: ${NODE_UID}
      dockerfile: Dockerfile-Frontend
    logging:
      options:
        max-size: '10m'
        max-file: '5'
    env_file:
      - .env
    volumes:
      - '/etc/passwd:/etc/passwd:ro'
    ports:
      - '3000:3000'
    restart: unless-stopped

# network config
networks:
  supaheroes-webserver-network:
    external: true
