- name: "install_docker : add docker gpg apt key"
  apt_key:
    url: https://download.docker.com/linux/ubuntu/gpg
    state: present
  become: true

- name: "install_docker : add docker repository"
  apt_repository:
    repo: deb https://download.docker.com/linux/ubuntu focal stable
    state: present
  become: true

- name: "install_docker : install docker engine"
  apt:
    pkg:
      - docker-ce
      - docker-ce-cli
      - containerd.io
      - docker-buildx-plugin
      - docker-compose-plugin
    state: latest
    update_cache: true
  become: true

- name: "install_docker : docker auto init"
  command: systemctl enable docker.service
  become: true

- name: "install_docker : containerd auto init"
  command: systemctl enable containerd.service
  become: true

- name: "install_docker : lazydocker"
  ansible.builtin.shell:
    executable: /bin/bash
    chdir: "/tmp"
    cmd: |
      export DIR=/usr/bin
      curl https://raw.githubusercontent.com/jesseduffield/lazydocker/master/scripts/install_update_linux.sh | bash
  become: true
