- name: create project dir
  ansible.builtin.file:
    path: "{{ website_root_dir }}"
    owner: "{{ user_node }}"
    group: "{{ user_node }}"
    state: directory
  become: true

- name: copy src to server
  ansible.posix.synchronize:
    src: "{{ local_dir }}/frontend-cms/"
    dest: "{{ website_root_dir }}/frontend-cms/"
    delete: yes
    recursive: yes
    archive: no
    rsync_opts:
      - "--include=src"
      - "--include=src/**"
      - "--include=public"
      - "--include=public/**"
      - "--include=package*.json"
      - "--include=tsconfig*"
      - "--include=vite*"
      - "--include=.npmrc"
      - "--include=index.html"
      - "--exclude=*"
      - "--no-motd"
  become: true
  become_user: "node"

- name: copy dockerfile to server
  ansible.builtin.copy:
    src: "{{ local_dir }}/frontend-cms/Dockerfile-Frontend"
    owner: "{{ user_node }}"
    group: "{{ user_node }}"
    dest: "{{ website_root_dir }}/frontend-cms/"

- name: copy dockercompose to server
  ansible.builtin.copy:
    src: "{{ local_dir }}/frontend-cms/docker-compose-frontend.yml"
    owner: "{{ user_node }}"
    group: "{{ user_node }}"
    dest: "{{ website_root_dir }}/frontend-cms/"

- name: frontend env
  template:
    src: "{{ playbook_dir }}/templates/env-frontend-cms.j2"
    owner: "{{ user_node }}"
    group: "{{ user_node }}"
    dest: "{{ website_root_dir }}/frontend-cms/.env"

- name: build docker-compose
  ansible.builtin.shell:
    executable: /bin/bash
    chdir: "{{ website_root_dir }}/frontend-cms/"
    cmd: |
      source .env && export $(sed '/^#/d' '.env' | cut -d= -f1)
      docker compose -f docker-compose-frontend.yml --env-file .env up -d --build --force-recreate 
      docker image prune -f
