services:
  supaheroes_frontend_cms:
    image: supaheroes_frontend_cms:1.0.0
    container_name: supaheroes_frontend_cms
    networks:
      - supaheroes-webserver-network
    build:
      context: ./
      args:
        NODE_UID: ${NODE_UID}
      dockerfile: Dockerfile-Frontend
    logging:
      options:
        max-size: '10m'
        max-file: '5'
    env_file:
      - .env
    volumes:
      - '/etc/passwd:/etc/passwd:ro'
    ports:
      - '4173:4173'
    restart: unless-stopped

# network config
networks:
  supaheroes-webserver-network:
    external: true
