FROM node:18.16.0-alpine3.17

ARG NODE_UID

#RUN umask 0002

#RUN deluser --remove-home node \
#  && addgroup -S node -g $NODE_UID \
#  && adduser -S -G node -u $NODE_UID node

WORKDIR /home/node/frontend-cms/

COPY ./package*.json ./
COPY ./.npmrc ./

RUN npm ci

COPY ./tsconfig* ./
COPY ./vite* ./
COPY ./src ./src
COPY ./public ./public
COPY ./index.html ./
COPY ./.env ./.env

RUN npm run build

ENTRYPOINT ["npm", "run", "preview"]
#ENTRYPOINT ["tail", "-f", "/dev/null"]
