import { Create, Edit } from "@refinedev/mui";
import { Alert, Box, Grid, Typography } from "@mui/material";
import { useForm } from "@refinedev/react-hook-form";
import { IResourceComponentsProps } from "@refinedev/core";
import { FormProvider } from "react-hook-form";
import { Tabs } from "./form/tabs/tabs";
import { TextField } from "../../components/form/textfield";

export const CharCreate: React.FC<IResourceComponentsProps> = () => {
  const useFormMethods = useForm({
    defaultValues: {
      charName: "",
    },
  });

  const {
    saveButtonProps,
    refineCore: { formLoading },
  } = useFormMethods;

  return (
    <FormProvider {...useFormMethods}>
      <Create isLoading={formLoading} saveButtonProps={saveButtonProps}>
        <Box
          component="form"
          sx={{
            display: "flex",
            flexDirection: "column",
          }}
        >
          <Typography variant="subtitle1" gutterBottom paddingX={1}>
            Welcome to the Character Creation Module!
            <br />
            The process is simple: just enter the character's name, and the AI
            will generate all the content for you. But you can also edit the
            content if you want to.
          </Typography>
          <Typography variant="body2" gutterBottom paddingX={1}>
            The AI will generate the character's story, attributes, strengths,
            weaknesses, and some images.
            <br />
            The prompt that describes the character is also generated by AI, and
            then another AI will be prompted to create the images.
          </Typography>

          <Grid container spacing={1} direction="row">
            <Grid item xs={12} marginTop={1}>
              <TextField
                fieldName="name"
                i18nPath="char.fields"
                helperText="ex: John Snow from Game Of Thrones (it's better to be specific)"
              />
            </Grid>

            <Grid item xs={12} marginTop={1}>
              <Alert severity="warning">
                Please note that due to the complexity and richness of the
                generated content, the creation process may take a few minutes.
              </Alert>
            </Grid>
          </Grid>
        </Box>
      </Create>
    </FormProvider>
  );
};
